# Generated by Django 4.2.16 on 2024-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210313_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='tx_ref',
            field=models.CharField(default=123456, max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
